Models/BidStaff.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace NBDPrototype.Models
{
    public class BidStaff
    {
        public int ID { get; set; }
        public int BidId { get; set; }
        public Bid Bid { get; set; }

        public int StaffId { get; set; }
        public Staff Staff { get; set; }

        [Required(ErrorMessage = "State estimated hours.")]
        [Display(Name = "Hours")]
        public int BidStaffTotalHours { get; set; }

        [Display(Name = "Markup Cost")]
        [Required(ErrorMessage = "You must enter the amount.")]
        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(9,2)")]//So only 5 bytes to store in SQL Server
        [Range(0, 9999999.99, ErrorMessage = "Invalid Amount.")]
        public decimal BidStaffMarkup { get; set; }

        [DataType(DataType.Currency)]
        [Column(TypeName = "decimal(9,2)")]
        public decimal? TotalStaffEarnings
        {
            get
            {
                return (BidStaffTotalHours * Staff?.LabourCost) + BidStaffMarkup;
            }
        }
    }
}

Controllers/BidsController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NBDPrototype.Data;
using NBDPrototype.Models;
using NBDPrototype.ViewModels;

namespace NBDPrototype.Controllers
{
    public class BidsController : BaseController
    {

        private readonly NBDContext _context;

        public BidsController(NBDContext context)
        {
            _context = context;
        }

        // GET: Bids
        public async Task<IActionResult> Index(int? id, int? biditemID)
        {
            var viewModel = new BidVM();
            viewModel.Bids = await _context.Bids
                .Include(i => i.Projects)
                .Include(i => i.BidItems)
                    .ThenInclude(i => i.Item)
                    .ThenInclude(i => i.ItemType)
                .Include(i => i.Statuses)
                .Include(i => i.BidStaffs)
                    .ThenInclude(i => i.Staff)
                    .ThenInclude(i => i.Labour)
                .AsNoTracking()
                .ToListAsync();

            if (id != null)
            {
                ViewData["BidId"] = id.Value;
                Bid bid = viewModel.Bids.Where(
                    i => i.ID == id.Value).Single();
                viewModel.Items = bid.BidItems.Select(s => s.Item);
                viewModel.Staffs = bid.BidStaffs.Select(s => s.Staff);
            }

            //dynamic nbdmodel = new ExpandoObject();
            //var nBDContext = _context.Bids.Include(b => b.Projects).Include(b => b.Statuses);
            //nbdmodel.BidItems = Get
            //return View(await nBDContext.ToListAsync());
            return View(viewModel);
        }

        // GET: Bids/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bid = await _context.Bids
                .Include(b => b.Projects)
                .Include(b => b.Statuses)
                .Include(b => b.BidItems)
                    .ThenInclude(b => b.Item)
                    .ThenInclude(b => b.ItemType)
                .Include(b => b.BidStaffs)
                    .ThenInclude(b => b.Staff)
                    .ThenInclude(b => b.Labour)
                .FirstOrDefaultAsync(m => m.ID == id); 
            if (bid == null)
            {
                return NotFound();
            }

            return View(bid);
        }

        // GET: Bids/Create


        //[Route("/Bids/Create", Name = "bidscreate")]
        public IActionResult Create()
        {
            PopulateDropDownLists();
            //Bid bid = new Bid();
            //PopulateBidItemList(bid);
            //ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID");
            //ViewData["StatusId"] = new SelectList(_context.Statuses, "ID", "ID");
            return View();
        }

        // POST: Bids/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,ProjectID,Date,StartDate,ClosingDate,StatusId,IsApproved")] Bid bid)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bid);
                await _context.SaveChangesAsync();
                //try to create and save data into database
                NotifyCreate("Data created successfully");
                return RedirectToAction(nameof(Index));
            }
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID", bid.ProjectID);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "ID", "ID", bid.StatusId);
            return View(bid);
        }


        // GET: Bids/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bid = await _context.Bids.FindAsync(id);
            if (bid == null)
            {
                return NotFound();
            }
            //ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID", bid.ProjectID);
            //ViewData["StatusId"] = new SelectList(_context.Statuses, "ID", "ID", bid.StatusId);
            PopulateDropDownLists();
            return View(bid);
        }

        // POST: Bids/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,ProjectID,Date,StartDate,ClosingDate,Amount,StatusId,IsApproved")] Bid bid)
        {
            if (id != bid.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bid);
                    await _context.SaveChangesAsync();
                    //try to save data into database
                    NotifyUpdate("Data saved successfully");

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BidExists(bid.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //PopulateBidItemList(bid);
            //ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "ID", bid.ProjectID);
            //ViewData["StatusId"] = new SelectList(_context.Statuses, "ID", "ID", bid.StatusId);
            PopulateDropDownLists();
            return View(bid);
        }

        // GET: Bids/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bid = await _context.Bids
                .Include(b => b.Projects)
                .Include(b => b.Statuses)
                .FirstOrDefaultAsync(m => m.ID == id);
            if (bid == null)
            {
                return NotFound();
            }

            return View(bid);
        }

        // POST: Bids/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var bid = await _context.Bids.FindAsync(id);
            _context.Bids.Remove(bid);
            await _context.SaveChangesAsync();
            try
            {
                NotifyDelete("Data deleted successfully!", notificationType: NotificationType.success);
                //throw new UnauthorizedAccessException();
            }
            catch (UnauthorizedAccessException)
            {
                NotifyDelete("Could not delete data!", notificationType: NotificationType.error);

            }
            return RedirectToAction(nameof(Index));
        }

        private void PopulateDropDownLists(Bid bid = null)
        {
            ViewData["ProjectID"] = new SelectList(_context.Projects, "ID", "Name", bid?.ProjectID);
            ViewData["StatusId"] = new SelectList(_context.Statuses, "ID", "BidStatus", bid?.StatusId);
        }

        private bool BidExists(int id)
        {
            return _context.Bids.Any(e => e.ID == id);
        }

        


        //private void PopulateBidItemList(Bid bid)
        //{
        //    var allOptions = _context.Items;
        //    var currentOptionsHS = new HashSet<int>(bid.BidItems.Select(b => b.ItemId));
        //    var selected = new List<BidItemVM>();
        //    var available = new List<BidItemVM>();
        //    foreach (var s in allOptions)
        //    {
        //        if (currentOptionsHS.Contains(s.ID))
        //        {
        //            selected.Add(new BidItemVM
        //            {
        //                ID = s.ID,
        //                BIName = s.Description
                        

        //            });
        //        }
        //        else
        //        {
        //            available.Add(new BidItemVM
        //            {
        //                ID = s.ID,
        //                BIName = s.Description
        //            });
        //        }
        //    }

        //    ViewData["selOpts"] = new MultiSelectList(selected.OrderBy(s => s.BIName), "ID", "BIName");
        //    ViewData["availOpts"] = new MultiSelectList(available.OrderBy(s => s.BIName), "ID", "BIName");
        //}
    }
}

Views/BidStaffs/Add.cshtml
@model NBDPrototype.Models.BidStaff

@{
    ViewData["Title"] = "Add Staff";
}


<h2></h2>
<hr />
<form asp-action="Add">
    <input type="hidden" name="BidId" value="@Model.BidId" />
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group row">
                <div class="col-3">
                    <label asp-for="StaffId"></label>
                </div>
                <div class="col-6">
                    <select asp-for="StaffId" class="form-control" asp-items="ViewBag.StaffId">
                        <option value="">Select an Employee</option>
                    </select>
                </div>
                <span asp-validation-for="StaffId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BidStaffTotalHours" class="control-label"></label>
                <input asp-for="BidStaffTotalHours" class="form-control" type="number" min="0" />
                <span asp-validation-for="BidStaffTotalHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BidStaffMarkup" class="control-label"></label>
                <input asp-for="BidStaffMarkup" class="form-control" type="number" min="0" />
                <span asp-validation-for="BidStaffMarkup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>
<div>
    <a href='@ViewData["returnURL"]'>Back to Bid</a>
</div>

Views/BidStaffs/Index.cshtml
@model IEnumerable<NBDPrototype.Models.BidStaff>


@{
    ViewData["Title"] = "Index";
    NBDPrototype.Models.Bid bid = (NBDPrototype.Models.Bid)ViewBag.Bid;
}

<p> </p>
<div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => bid.Projects)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => bid.Projects.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => bid.Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => bid.Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => bid.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => bid.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => bid.ClosingDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => bid.ClosingDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => bid.Amount)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => bid.Amount)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => bid.Statuses)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => bid.Statuses.BidStatus)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => bid.IsApproved)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => bid.IsApproved)
        </dd>
    </dl>
</div>

<form asp-action="Index" method="get">
    <input type="hidden" name="sortDirection" value="@ViewData["sortDirection"]" />
    <input type="hidden" name="sortField" value="@ViewData["sortField"]" />
    <input type="hidden" name="BidId" value="@bid.ID" />
    <a asp-action="Index" asp-controller="BidItems" asp-route-BidId="@bid.ID" class="btn btn-info btn-lg text-white " tooltip-test" title="View Item Details"><i class="fas fa-info-circle">View Items</i></a>
    <h2>Bid Items</h2>
    <dl class="dl-horizontal">
        @*<dt>
                <button class="btn @(ViewData["Filtering"])" type="button" data-toggle="collapse" id="filterToggle" data-target="#collapseFilter" aria-expanded="false" aria-controls="collapseFilter">
                    Filter
                </button>
            </dt>*@
        @*<dd>
                <div class="form-horizontal">
                    <div class="collapse card card-body bg-light" style="padding-top: 10px; padding-bottom: 0px;" id="collapseFilter">
                        <div class="form-row">
                            <div class="form-group col-md-4 ml-md-3">
                                <label class="control-label">Item Type:</label>
                                @Html.DropDownList("ItemId", null, "All Reasons", htmlAttributes: new { @class = "form-control" })
                            </div>
                            <div class="form-group col-md-3 align-self-end">
                                <input type="submit" name="actionButton" value="Apply" class="btn btn-primary" />
                                <a asp-action="Index" asp-route-BidId="@bid.ID">Clear</a>
                            </div>
                        </div>
                    </div>
                </div>
            </dd>*@
        <dt>
        </dt>
        <dd>
            <div>
                <table class="table">
                    <colgroup>
                        <col span="1" />
                        <col span="1" />
                        <col span="1" />
                        <col span="1" />
                    </colgroup>
                    <tr>
                        <th>
                            <input type="submit" name="actionButton" value="Employee" class="btn btn-link" />
                        </th>
                        <th>
                            <input type="submit" name="actionButton" value="Hourly Wage" class="btn btn-link" /><br />
                        </th>
                        <th>
                            <input type="submit" name="actionButton" value="Est. Total hours" class="btn btn-link" />
                        </th>
                        <th>
                            <input type="submit" name="actionButton" value="Markup" class="btn btn-link" />
                        </th>
                        <th>
                            <input type="submit" name="actionButton" value="Total Costs Per" class="btn btn-link" />
                        </th>
                        <th>
                            <a asp-controller="BidStaffs" asp-action="Add" asp-route-BidId="@bid.ID">
                                <span class="btn btn-success"><strong>&#x271A; Add</strong></span>
                            </a>
                        </th>
                    </tr>

                    @foreach (var item in Model)
                    {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Staff.StaffFullNameAndJob)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Staff.LabourCost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BidStaffTotalHours)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.BidStaffMarkup)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TotalStaffEarnings)
                    </td>
                    <td>
                        <a asp-controller="BidStaffs" asp-action="Update" asp-route-id="@item.ID">
                            <span class="btn btn-sm btn-outline-primary">&#x270D;</span>
                        </a>
                        <a asp-controller="BidStaffs" asp-action="Remove" asp-route-id="@item.ID">
                            <span class="btn btn-sm btn-outline-danger">&#x274C</span>
                        </a>
                    </td>
                </tr>
                    }
                </table>
            </div>
        </dd>
    </dl>
    <partial name="_PagingNavBar" />
</form>
<div>
    <a asp-action="Edit" asp-controller="Bids" asp-route-id="@bid.ID">Edit</a> |
    <a href='@ViewData["returnURL"]'>Back to Bid List</a>
</div>
@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('[data-toggle="popover"]').popover();
        });
    </script>
}

Views/BidStaffs/Remove.cshtml
@model NBDPrototype.Models.BidStaff

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BidStaff</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bid.ID)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Staff)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Staff.StaffFirstName)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BidStaffTotalHours)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BidStaffTotalHours)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BidStaffMarkup)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BidStaffMarkup)
        </dd>
    </dl>
    
    <form asp-action="Remove">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/BidStaffs/Update.cshtml
@model NBDPrototype.Models.BidStaff

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BidStaff</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <input type="hidden" name="BidId" value="@Model.BidId" />
            <div class="form-group">
                <label asp-for="BidId" class="control-label"></label>
                <select asp-for="BidId" class="form-control" asp-items="ViewBag.BidId"></select>
                <span asp-validation-for="BidId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StaffId" class="control-label"></label>
                <select asp-for="StaffId" class="form-control" asp-items="ViewBag.StaffId"></select>
                <span asp-validation-for="StaffId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BidStaffTotalHours" class="control-label"></label>
                <input asp-for="BidStaffTotalHours" class="form-control" />
                <span asp-validation-for="BidStaffTotalHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BidStaffMarkup" class="control-label"></label>
                <input asp-for="BidStaffMarkup" class="form-control" />
                <span asp-validation-for="BidStaffMarkup" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}